{{- $fullName := (print .Release.Name "-check-links") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-sort-upload-script
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
data:
  check_links-sort-upload.sh: |-
    cd /app/check-links
    pip install -r requirements.txt
    python check_links.py --output-dir=/check_links
    python check_links_sort.py --input-dir=/check_links
