{{- $fullName := (print .Release.Name "-check-links") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-sort-upload-script
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
data:
  check_links-sort-upload.sh: |-
    cd /usr/lib/ckan/venv/src/ckanext-datagovuk/bin/python_scripts
    pip install -r check_links-requirements.txt
    python check_links.py --output-dir=/check_links
    python check_links_sort.py --input-dir=/check_links
