{{- $fullName := (print .Release.Name "-check-links-process") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-script
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
data:
  check_links-process.sh: |-
    cd /usr/lib/ckan/venv/src/ckanext-datagovuk/bin/python_scripts
    python check_links_download.py

    export REPORT_TIMESTAMP=20260619T0801
    export STATE=deleted

    python process_check_links_report.py --input "/check_links/check_links_report_$REPORT_TIMESTAMP.csv" --output-dir /check_links --set-state "$STATE" --mode live
    python solr_reindex_package_ids.py --input-file "/check_links/packages_to_reindex_$REPORT_TIMESTAMP.txt"
