{{- $ckanEfs := print .Release.Name "-ckan-efs" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-check-links-pvc
spec:
  resources:
    requests:
      storage: {{ .Values.ckan.checkLinks.persistence.size | default "1Gi" }}
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $ckanEfs }}
      app.kubernetes.io/component: {{ $ckanEfs }}
