{{- if .Values.checklinks.report.enabled }}
{{- $fullName := print .Release.Name "-check-links-process" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullName }}
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
  labels:
    app.kubernetes.io/arch: {{ default "amd64" .Values.arch }}
spec:
  schedule: "0 0 * * 0"  # At 00:00 on Sunday
  suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      name: {{ $fullName }}
      labels:
        app.kubernetes.io/arch: {{ default "amd64" .Values.arch }}
    spec:
      template:
        metadata:
          name: {{ $fullName }}
          labels:
            app.kubernetes.io/arch: {{ default "amd64" .Values.arch }}
        spec:
          initContainers:
            - name: config-set
              image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "check-links" "files" $.Files) }}'
              command: [ "/bin/sh", "-c", '. /init/init.sh']
              imagePullPolicy: Always
              env:
                {{ include "ckan.environment-variables" . | nindent 16 }}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              volumeMounts:
                - name: production-ini
                  mountPath: /map
                  readOnly: true
                - name: config
                  mountPath: /config
                - name: ckan-init
                  mountPath: /init
          containers:
            - name: check-links-script
              image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "check-links" "files" $.Files) }}'
              workingDir: /app/check-links
              imagePullPolicy: Always
              command: [ "bash", "-c", ". chart/check_links-process.sh" ]
              env:
                {{- include "check-links.environment-variables" . | nindent 16 }}
              volumeMounts:
                - name: config
                  mountPath: /config
                  readOnly: true
                - name: check-links-output
                  mountPath: /check_links
                - name: check-links-process-script
                  mountPath: /app/check-links/chart
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 900
            runAsGroup: 900
            fsGroup: 900
            seccompProfile:
              type: RuntimeDefault
          volumes:
            - name: ckan-init
              configMap:
                name: {{ .Release.Name }}-ckan-init
            - name: production-ini
              configMap:
                name: {{ .Release.Name }}-{{ .Values.ckan.ckanIniConfigMap }}
            - name: config
              emptyDir: {}
            - name: check-links-process-script
              configMap:
                name: {{ $fullName }}-script
            - name: check-links-output
              emptyDir: {}
          {{- if eq "arm64" .Values.arch }}
          tolerations:
            - key: arch
              operator: Equal
              value: {{ .Values.arch }}
              effect: NoSchedule
          nodeSelector:
            kubernetes.io/arch: {{ .Values.arch }}
          {{- end }}
{{- end }}