apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-check-links
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
  labels:
    app.kubernetes.io/arch: {{ default "amd64" .Values.arch }}
spec:
  schedule: "0 9 * * *"
  suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      name: {{ .Release.Name }}-check-links
      labels:
        app.kubernetes.io/arch: {{ default "amd64" .Values.arch }}
    spec:
      template:
        metadata:
          name: {{ .Release.Name }}-check-links
          labels:
            app.kubernetes.io/arch: {{ default "amd64" .Values.arch }}
        spec:
          containers:
            - name: check-links-script
              image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "ckan" "files" $.Files) }}'
              workingDir: /usr/lib/ckan/venv/src/ckanext-datagovuk/bin/python_scripts
              imagePullPolicy: Always
              # command: [ "/bin/sh", "-c", "python check_links.py --output-dir=/" ]
              command: [ "/bin/sh", "-c", "sleep 10000" ]
              env:
                {{- include "ckan.environment-variables" . | nindent 16 }}
              volumeMounts:
                - name: check-links-output
                  mountPath: /
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 900
            runAsGroup: 900
            fsGroup: 900
            seccompProfile:
              type: RuntimeDefault
          volumes:
            - name: check-links-output
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-check-links-efs-pv-pvc
          {{- if eq "arm64" .Values.arch }}
          tolerations:
            - key: arch
              operator: Equal
              value: {{ .Values.arch }}
              effect: NoSchedule
          nodeSelector:
            kubernetes.io/arch: {{ .Values.arch }}
          {{- end }}
