{{- $fullName := (print .Release.Name "-check-links-deletion") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-script
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
data:
  check_links-deletion.sh: |-
    cd /usr/lib/ckan/venv/src/ckanext-datagovuk/bin/python_scripts
    python check_links_download.py
    python process_check_links_report.py --input /check_links/check_links_report_20260607T0000.csv --output-dir /check_links --set-state deleted --mode live
