apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.persistence.persistentVolumeClaimName }}
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
