apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
spec:
  serviceName: "redis"
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
        app.kubernetes.io/arch: {{ .Values.redis.arch }}
    spec:
      {{- if .Values.redis.persistence.enabled }}
      initContainers:
        - name: fix-volume-permissions
          image: {{ .Values.redis.image }}
          command: [ sh, -c, "chown -R redis:redis /data"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: data
              mountPath: /data
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - name: redis
              containerPort: 6379
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
      {{- if .Values.redis.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.redis.persistence.persistentVolumeClaimName }}
      {{- end }}
      {{- if eq "arm64" .Values.redis.arch }}
      tolerations:
        - key: arch
          operator: Equal
          value: {{ .Values.redis.arch }}
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/arch: {{ .Values.redis.arch }}
      {{- end }}