apiVersion: v1
kind: Secret
metadata:
  name: ckan
type: Opaque
stringData:
  sqlalchemy_url: "postgresql://ckan:ckan@ckan-dev-postgres/ckan"
  publish_sqlalchemy_url: "postgresql://ckan:ckan@ckan-dev-postgres/publish"
  solr_password: "ckan"
  smtp_password: "ckan"
  beaker_session_secret: "9EZiPwkeS+cZpqb0VDWrN+Q0M"
  aws_access_key_id: "test"
  aws_secret_access_key: "test"
---
apiVersion: v1
kind: Secret
metadata:
  name: datagovuk
type: Opaque
stringData:
  publish_sqlalchemy_url: "postgresql://ckan:ckan@ckan-dev-postgres/publish"
  secret_key_base: "dummy"
  zendesk_api_key: "dummy"
  zendesk_username: "dummy"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr
spec:
  resources:
    requests:
      storage: 300Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
