apiVersion: v1
kind: Namespace
metadata:
  name: datagovuk
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Secret
metadata:
  name: ckan
  namespace: datagovuk
type: Opaque
stringData:
  sqlalchemy_url: "postgresql://ckan:ckan@ckan-dev-postgres/ckan"
  solr_password: "ckan"
  smtp_password: "ckan"
  beaker_session_secret: "9EZiPwkeS+cZpqb0VDWrN+Q0M"
  beaker_session_validate_key: "UIZYT0m866FiFutxNP2cac2892i"
  aws_access_key_id: "test"
  aws_secret_access_key: "test"
---
apiVersion: v1
kind: Secret
metadata:
  name: datagovuk
  namespace: datagovuk
type: Opaque
stringData:
  secret_key_base: "dummy"
  zendesk_api_key: "dummy"
  zendesk_username: "dummy"
  find_sentry_dsn: "dummy"
  govuk_app_domain: "www.gov.uk"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: datagovuk
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce