apiVersion: v1
kind: Namespace
metadata:
  name: datagovuk
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Secret
metadata:
  name: ckan
  namespace: datagovuk
type: Opaque
stringData:
  aws_access_key_id: "test"
  aws_secret_access_key: "test"