apiVersion: v1
kind: Secret
metadata:
  name: ckan
type: Opaque
stringData:
  sqlalchemy_url: "postgresql://ckan:ckan@ckan-test-postgres/ckan"
  solr_password: "ckan"
  smtp_password: "ckan"
  beaker_session_secret: "9EZiPwkeS+cZpqb0VDWrN+Q0M"
  aws_access_key_id: "test"
  aws_secret_access_key: "test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
