{{- if .Values.scripts.enabled }}
{{- $fullName := print .Release.Name "-ckan-scripts" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
    app.kubernetes.io/component: app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.ckan.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
        app.kubernetes.io/name: {{ $fullName }}
        app.kubernetes.io/arch: {{ default "amd64" .Values.arch }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 900
        runAsGroup: 900
        fsGroup: 900
        seccompProfile:
          type: RuntimeDefault
      {{ if .Values.ckan.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.ckan.serviceAccount.name | default (print "ckan-" .Release.Name) }}
      {{- end }}
      initContainers:
        - name: config-set
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "ckan" "files" $.Files) }}'
          command: [ "/bin/sh", "-c", '. /init/init.sh']
          imagePullPolicy: Always
          env:
            {{ include "ckan.environment-variables" . | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: production-ini
              mountPath: /map
              readOnly: true
            - name: config
              mountPath: /config
            - name: ckan-init
              mountPath: /init
            - name: prom-tmp
              mountPath: /prom_tmp
        - name: script-set
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "ckan" "files" $.Files) }}'
          command: [ "/bin/sh", "-c", '. /ckan-script-set/script-set.sh']
          imagePullPolicy: Always
          env:
            {{ include "scripts.environment-variables" . | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: production-ini
              mountPath: /map
              readOnly: true
            - name: config
              mountPath: /config
            - name: ckan-init
              mountPath: /init
            - name: ckan-script-set
              mountPath: /ckan-script-set
            - name: scripts
              mountPath: /scripts
      containers:
        - name: ckan
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "ckan" "files" $.Files) }}'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.ckan.appPort }}
            - name: metrics
              containerPort: {{ .Values.monitoring.metricsPort }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: prom-tmp
              mountPath: /prom_tmp
            - name: ckan-scripts
              mountPath: /ckan-scripts
            - name: scripts
              mountPath: /scripts
          command: ["/bin/sh", "-c"]
          args: [ ". /ckan-scripts/script.sh" ]
          env:
            {{ include "scripts.environment-variables" . | nindent 12 }}
            - name: PROMETHEUS_MULTIPROC_DIR
              value: /prom_tmp
            - name: PROMETHEUS_METRICS_PORT
              value: "9394"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          {{- with .Values.ckan.appResources }}
          resources:
            {{- . | toYaml | trim | nindent 12 }}
          {{- end }}
          {{- if .Values.ckan.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 60
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 5
            successThreshold: 3
            timeoutSeconds: 30
          startupProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 60
            failureThreshold: 60
            periodSeconds: 10
            timeoutSeconds: 60
          {{- end }}
      volumes:
        - name: ckan-init
          configMap:
            name: {{ .Release.Name }}-ckan-init
        - name: production-ini
          configMap:
            name: {{ .Release.Name }}-{{ .Values.ckan.ckanIniConfigMap }}
        - name: config
          emptyDir: {}
        - name: {{ .Values.ckan.nginx.configMap.name | default (printf "%s-nginx-conf" $fullName) }}
          configMap:
            name: {{ .Values.ckan.nginx.configMap.name | default (printf "%s-nginx-conf" $fullName) }}
        - name: ckan-script-set
          configMap:
            name: {{ $fullName }}-set
        - name: ckan-scripts
          configMap:
            name: {{ $fullName }}
        - name: scripts
          emptyDir: {}
        - name: prom-tmp
          emptyDir: {}
      {{- if eq "arm64" .Values.arch }}
      tolerations:
        - key: arch
          operator: Equal
          value: {{ .Values.arch }}
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/arch: {{ .Values.arch }}
      {{- end }}
{{- end }}
