{{- if .Values.scripts.enabled }}
{{- $fullName := (print .Release.Name "-ckan-scripts") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
data:
  script.sh: |-
    # gunicorn --bind 0.0.0.0:5000 wsgi:application --timeout 120 --workers 8 &
    cd /scripts
    python script.py {{ .Values.scripts.args }}
{{- end }}