{{- if .Values.find.ingress.enabled }}
{{- $ephemeralPath := print $.Values.environment ".ephemeral" -}}
{{- $eksPath := print "eks." $.Values.environment -}}
{{- $environmentPath := hasPrefix "eph-" $.Values.environment | ternary $ephemeralPath $eksPath -}}
{{- with .Values.find.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: find
  {{- if not (empty .annotations) }}
  annotations:
    {{- toYaml .annotations | trim | nindent 4 }}
  {{- end }}
spec:
  {{ if not (empty .ingressClassName) }}ingressClassName: {{ .ingressClassName }}{{ end }}
  rules:
    - host: find.{{ $environmentPath }}.govuk.digital
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-find
                port:
                  number: 3000
{{- end }}
{{- end }}
