{{- range $app := (list "find" "frontend-find") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $app }}
spec:
  selector:
    app: {{ $.Release.Name }}-{{ $app }}
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
---
{{- end }}
{{ if eq "test" .Values.environment }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-datagovuk
spec:
  selector:
    app: {{ $.Release.Name }}-datagovuk
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
---
{{- end }}