apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-find
spec:
  selector:
    app: {{ .Release.Name }}-find
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
