{{- if .Values.script.enabled }}
{{- $fullName := (print .Release.Name "-ckan-script") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
data:
  script.sh: |-
    cd /script
    {{- if .Values.script.requirementsUrl }}
    pip install -r requirements.txt
    {{- end }}
    python script.py {{ .Values.script.args }}
    {{- if .Values.script.catOutput }}
    echo "Script output:"
    echo "==============================="
    cat output.file
    {{- end }}
{{- end }}
