{{- if .Values.script.enabled }}
{{- $fullName := (print .Release.Name "-ckan-script") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
data:
  script.sh: |-
    cd /script
    {{- if .Values.script.requirementsUrl }}
    pip install -r requirements.txt
    {{- end }}
    {{- if .Values.script.url }}
    python script.py {{ .Values.script.args }}
    {{- end }}
    {{- if .Values.script.catOutput }}
    echo "Script output:"
    echo "==============================="
    find -name "*not_deleted*.csv" -exec cat {} \;
    {{- end }}
    {{- if .Values.script.url_2 }}
    python script-2.py {{ .Values.script.args_2 }}
    {{- end }}
    {{- if .Values.script.keep_up_time }}
    echo "This pod will terminate at "$(date --date='{{ .Values.script.keep_up_time }} seconds')
    trap : TERM INT; sleep {{ .Values.script.keep_up_time }} & wait
    {{- end }}
{{- end }}
