{{- if .Values.script.enabled }}
{{- $fullName := (print .Release.Name "-ckan-script") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
data:
  script.sh: |-
    cd /script
    python script.py {{ .Values.script.args }}
{{- end }}
