{{- if .Values.script.enabled }}
{{- $fullName := (print .Release.Name "-ckan-script-set") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
data:
  script-set.sh: |-
    wget "{{ .Values.script.url }}" -O "/script/script.py"
{{- end }}
