{{- if .Values.opensearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.opensearch.persistence.persistentVolumeClaimName }}
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
{{- end }}
