apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-opensearch-sts
spec:
  selector:
    app: {{ .Release.Name }}-opensearch-sts
  ports:
    - name: host-port
      port: 9200
      targetPort: host-port
    - name: node-port
      port: 9600
      targetPort: node-port
