apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pycsw
spec:
  replicas: {{ .Values.pycsw.count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pycsw
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pycsw
    spec:
      securityContext:
        runAsUser: 900
        runAsGroup: 900
        fsGroup: 900
      {{- include "ckan.pycsw-init" . | nindent 6 }}
      containers:
        - name: pycsw
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "pycsw" "files" $.Files) }}'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /config
          command: ["/bin/sh", "-c"]
          args: {{ .Values.pycsw.args }}
          env:
            - name: PYCSW_CONFIG
              value: /config/pycsw.cfg
            {{ include "ckan.environment-variables" . | nindent 12 }}
          {{- if .Values.pycsw.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 3
          {{- end }}
      {{ include "ckan.pycsw-volumes" . | nindent 6 }}
