apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pycsw-init
data:
  init.sh: |
    # copy config files first 
    cp /map/production.ini /config
    cp /pycsw/pycsw.cfg /config
    cp $CKAN_VENV/src/ckan/who.ini /config

    # update production.ini
    ckan config-tool $CKAN_INI "ckan.plugins = harvest ckan_harvester spatial_metadata spatial_query spatial_harvest_metadata_api gemini_csw_harvester gemini_waf_harvester gemini_doc_harvester"
    ckan config-tool $CKAN_INI "who.config_file = /config/who.ini"
    # set i18n directory to ckan default
    ckan config-tool $CKAN_INI "ckan.i18n_directory=/usr/lib/ckan/venv/src/ckan/ckan/i18n"

    # Set CKAN_SQLALCHEMY_URL for database url
    sed "s|database=\${CKAN_SQLALCHEMY_URL}|database=$CKAN_SQLALCHEMY_URL|g" -i /config/pycsw.cfg

    # run init script
    /pycsw-entrypoint.sh
