environment: test

ckan:
  replicaCount: 1
  serviceAccount:
    enabled: false
    iamRoleARN: ""
  appPort: 5000
  args: ["gunicorn --bind 0.0.0.0:5000 wsgi:application --timeout 120 --workers 8"]
  ingress:
    enabled: true
    host: ckan.dev.govuk.digital
    ingressClassName: ""
    annotations:
    tls:
      enabled: false
  probes:
    enabled: false
  config:
    dbInit: true
    site:
      id: "dgu"
      url: "http://ckan.dev.govuk.digital:8081"
      title: "dev.data.gov.uk"
      description: "Data publisher"
    mock_harvest_source: "https://ckan-static-mock-harvest-source.cloudapps.digital/"
    sqlalchemyUrlSecretKeyRef:
      name: ckan
      key: sqlalchemy_url
    dbHost: ""
    redis:
      host: "dgu-shared-dev-redis"
      port: "6379"
      dbNumber: "1"
    beakerSessionSecretKeyRef:
      name: ckan
      key: beaker_session_secret
    solr:
      url: ""
      user: ""
      passwordSecretKeyRef:
        name: ckan
        key: solr_password
    smtp:
      server: "localhost:1025"
      user: ""
      passwordSecretKeyRef:
        name: ckan
        key: smtp_password
      mailFrom: ""
      starttls: "False"
    s3:
      useIamServiceAccount: false
      bucketName: ""
      urlPrefix: ""
      regionName: ""
      credentials:
        awsAccessKeyIdSecretKeyRef:
          name: ckan
          key: aws_access_key_id
        awsSecretAccessKeySecretKeyRef:
          name: ckan
          key: aws_secret_access_key

  service:
    annotations: {}
    port: 80

  nginx:
    image:
      repository: nginx
      pullPolicy: Always
      tag: stable
    port: 8080
    proxyConnectTimeout: 2s
    proxyReadTimeout: 30s
    clientMaxBodySize: 50M
    configMap:
      create: true
      name: ""
    extraVolumeMounts: []
    denyCrawlers: false
    safelist:
      # Used by: ckan.publishing.service.gov.uk
      # Used for: internationalisation of form controls
      - "/i18n"

      # Used by: ckan.publishing.service.gov.uk
      # Used for: finding members
      - "/2/util/user/autocomplete"

      # Used by: datagovuk_publish
      # Used for: ckan_v26_ckan_org_sync
      - "/action/organization_list"
      - "/action/organization_show"

      # Used by: datagovuk_publish
      # Used for: ckan_v26_package_sync job
      # Used by: pycsw data load in ckanext-spatial
      # Used for: syncing csw with ckan database
      - "/search/dataset"

      # Used by: datagovuk_publish
      # Used for: ckan_v26_package_sync job
      - "/action/package_show"

      # Used by: datagovuk_publish
      # Used for: determining filetype
      - "/2/util/resource/format_autocomplete"

      # Used by: datagovuk_find
      # Used for: addtional metadata links for datasets
      - "/2/rest/harvestobject"

      # Additional endpoints requested by users
      - "/action/package_search"
      - "/action/package_list"
      - "/action/harvest_source_list"

solr:
  enabled: true
  persistence:
    enabled: false
    persistentVolumeClaimName: "solr"
  extraEnv:
    - name: SOLR_LOG_LEVEL
      value: WARN

# This postgres instance is for development purposes only
postgres:
  enabled: true
  image: ghcr.io/alphagov/postgis:13-3.1
  persistence:
    enabled: false
    persistentVolumeClaimName: "postgres"
redis:
  enabled: true
  image: redis:6.2.5-alpine3.14
dev:
  enabled: true
gather:
  replicaCount: 1
fetch:
  replicaCount: 1

pycsw:
  replicaCount: 1
  args: ["python $CKAN_VENV/src/pycsw/pycsw/wsgi.py"]
  probes:
    enabled: false

externalSecret:
  enabled: false
  name: ckan
  key: govuk/dgu/ckan
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

monitoring:
  enabled: false
