apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-opensearch
spec:
  selector:
    app: {{ .Release.Name }}-opensearch
  ports:
    - name: host-port
      protocol: TCP
      port: 9200
      targetPort: host-port
    - name: node-port
      protocol: TCP
      port: 9600
      targetPort: node-port
