{{- if $.Values.dev.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-static-harvest-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-static-harvest-source
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-static-harvest-source
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: static-harvest-source
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "static-harvest-source" "files" $.Files) }}'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 11088
{{- end }}