{{- if $.Values.dev.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-static-harvest-source
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-static-harvest-source
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-static-harvest-source
        app.kubernetes.io/arch: {{ default "amd64" .Values.arch }}
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: static-harvest-source
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "static-harvest-source" "files" $.Files) }}'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 11088
      {{- if eq "arm64" .Values.arch }}
      tolerations:
        - key: arch
          operator: Equal
          value: {{ .Values.arch }}
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/arch: {{ .Values.arch }}
      {{- end }}
{{- end }}
