{{- if $.Values.dev.enabled }}
{{- $environment := $.Values.is_ephemeral | ternary "ephemeral" $.Values.environment -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-static-harvest-source
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-static-harvest-source
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-static-harvest-source
        app.kubernetes.io/arch: {{ default "amd64" .Values.arch }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: static-harvest-source
          image: '{{ include "docker-uri" (dict "environment" $environment "app" "static-harvest-source" "files" $.Files) }}'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 11088
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      {{- if eq "arm64" .Values.arch }}
      tolerations:
        - key: arch
          operator: Equal
          value: {{ .Values.arch }}
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/arch: {{ .Values.arch }}
      {{- end }}
{{- end }}
