apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-check-links-output
spec:
  selector:
    app: {{ .Release.Name }}-check-links-output
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
