{{- if .Values.ckan.dbBackupSync.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ckan-db-backup-xaccount-sync
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.ckan.dbBackupSync.iamRoleARN }}
{{ end }}