apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  replicas: {{ .Values.gather.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
        app.kubernetes.io/arch: {{ default "amd64" .Values.arch }}
    spec:
      serviceAccountName: ckan
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["sleep 30000"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 900
            runAsGroup: 900
            seccompProfile:
              type: RuntimeDefault
            # allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            # runAsUser: 0
            # runAsGroup: 0
            allowPrivilegeEscalation: false
            # capabilities:
            #   add: ["NET_ADMIN"] 
