apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: datagovuk
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testrolebinding
  namespace: datagovuk
subjects:
  - kind: ServiceAccount
    name: default
    namespace: datagovuk
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
