apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-remove-duplicates
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: remove-duplicates
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "ckan" "files" $.Files) }}'
          imagePullPolicy: Always
          command: [ python, ../ckanext-datagovuk/bin/python_scripts/remove_duplicates.py, run ]
          env:
            {{- include "ckan.environment-variables" . | nindent 16 }}
          volumeMounts:
            - name: production-ini
              mountPath: /config
              readOnly: true
      volumes:
        - name: production-ini
          configMap:
            name: {{ .Release.Name }}-{{ .Values.ckan.ckanIniConfigMap }}
