apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release3-assumed
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, watch, list]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, watch, list]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release3-assumer
  namespace: apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: datagovuk
  name: datagovuk3-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
