environment: test

# arch determines whether the app should schedule on amd64 or arm64 nodes.
# TODO: remove `arch` once the ARM migration is complete and we're no longer
# running mixed-arch clusters.
arch: amd64

redis:
  replicaCount: 1
  enabled: true
  image: redis:6.2.5-alpine3.14
  persistence:
    enabled: true
    persistentVolumeClaimName: "redis"
