{{- with .Values.externalSecret }}
{{- if .enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .name }}"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    {{- toYaml .secretStoreRef | trim | nindent 4 }}
  dataFrom:
    - extract:
        key: {{ .key }}
{{- end }}
{{- end }}
