apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-find
spec:
  replicas: {{ .Values.find.count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-find
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-find
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        # runAsUser: 900
        # runAsGroup: 900
        # fsGroup: 900
      containers:
        - name: find
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "find" "files" $.Files) }}'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          command: ["/bin/sh", "-c"]
          args: {{ .Values.find.args }}
          env:
            {{ include "find.environment-variables" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 60
            timeoutSeconds: 30
