apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-publish-org
spec:
  schedule: "{{ .Values.publish.config.org.schedule }}"
  concurrencyPolicy: Forbid  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: publish
              image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "publish" "files" $.Files) }}'
              imagePullPolicy: Always
              command: [ bin/rails, runner, "CKAN::V26::CKANOrgSyncWorker.new.perform" ]
              env:
                {{- include "publish.environment-variables" . | nindent 16 }}
          restartPolicy: OnFailure
