apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-solr-index-rebuild
spec:
  schedule: "0 8-22 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ckan
              image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "ckan" "files" $.Files) }}'
              imagePullPolicy: Always
              command: [ ckan, search-index, rebuild, -o, -i ]
              env:
                {{- include "ckan.environment-variables" . | nindent 16 }}
              volumeMounts:
                - name: production-ini
                  mountPath: /config
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: production-ini
              configMap:
                name: {{ .Release.Name }}-ckan-production-ini
