apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr
spec:
  resources:
    requests:
{{- if not $.Values.dev.enabled }}
      storage: 10Gi
{{- else }}
      storage: 1Gi
{{- end }}
  accessModes:
    - ReadWriteOnce
