ckan:
  count: 1
  serviceAccount:
    enabled: false
    iamRoleARN: ""
  args: ["gunicorn --bind 0.0.0.0:5000 wsgi:application --timeout 120 --workers 8"]
  ingress:
    enabled: true
    host: ckan.dev.govuk.digital
    ingressClassName: ""
    annotations:
    tls:
      enabled: false
  probes:
    enabled: false
  config:
    dbInit: true
    site:
      id: "dgu"
      url: "http://ckan.dev.govuk.digital:8081"
      title: "dev.data.gov.uk"
      description: "Data publisher"
    mock_harvest_source: "https://ckan-static-mock-harvest-source.cloudapps.digital/"
    sqlalchemyUrlSecretKeyRef:
      name: ckan
      key: sqlalchemy_url
    dbHost: ""
    redis:
      host: ""
      port: "6379"
      db_number: "1"
    beakerSessionSecretKeyRef:
      name: ckan
      key: beaker_session_secret
    solr:
      url: ""
      user: ""
      passwordSecretKeyRef:
        name: ckan
        key: solr_password
    smtp:
      server: "localhost:1025"
      user: ""
      passwordSecretKeyRef:
        name: ckan
        key: smtp_password
      mailFrom: ""
      starttls: "False"
    s3:
      useIamServiceAccount: false
      bucketName: ""
      urlPrefix: ""
      regionName: ""
      credentials:
        awsAccessKeyIdSecretKeyRef:
          name: ckan
          key: aws_access_key_id
        awsSecretAccessKeySecretKeyRef:
          name: ckan
          key: aws_secret_access_key

solr:
  enabled: true
  persistence:
    enabled: false
    persistentVolumeClaimName: "solr"
# This postgres instance is for development purposes only
postgres:
  enabled: true
  image: ghcr.io/alphagov/postgis:13-3.1
  persistence:
    enabled: false
    persistentVolumeClaimName: "postgres"
redis:
  enabled: true
  image: redis:6.2.5-alpine3.14
dev:
  enabled: true
gather:
  count: 1
fetch:
  count: 1

environment: test

pycsw:
  count: 1
  args: ["python $CKAN_VENV/src/pycsw/pycsw/wsgi.py"]
  probes:
    enabled: false
  ingress:
    enabled: true
    host: pycsw.data.gov.uk
    ingressClassName: ""
    annotations:
    tls:
      enabled: false

externalSecret:
  enabled: false
  name: ckan
  key: govuk/dgu/ckan
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

monitoring:
  enabled: false

opensearch:
  image: opensearchproject/opensearch
  persistence:
    enabled: false
    persistentVolumeClaimName: "opensearch"

publish:
  count: 1
  args: ["bundle exec rake db:migrate db:seed && bundle exec sidekiq"]
  probes:
    enabled: false
  config:
    sqlalchemyUrlSecretKeyRef:
      name: ckan
      key: publish_sqlalchemy_url
    dbHost: ""
    redis:
      host: ""
      port: "6379"
      db_number: "1"
    org:
      schedule: "*/10 * * * *"

find:
  count: 1
  args: ["bin/rails s -b 0.0.0.0"]
  ingress:
    enabled: true
    host: find.data.gov.uk
    ingressClassName: ""
    annotations:
    tls:
      enabled: false
