{{- if ne "test" $.Values.environment }}
{{- if .Values.datagovuk.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-datagovuk
  labels:
    app: {{ .Release.Name }}-datagovuk
    helm.sh/chart: govuk-dgu-charts
    app.kubernetes.io/name: datagovuk
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-datagovuk
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    metricRelabelings:
    - action: replace
      sourceLabels: ["__name__"]
      targetLabel: __name__
      regex: django_http_responses_total_by_status_total
      replacement: http_requests_total
    - action: replace
      sourceLabels: ["__name__"]
      targetLabel: __name__
      regex: django_http_requests_latency_including_middlewares_seconds_bucket
      replacement: http_request_duration_seconds_bucket
    - action: replace
      sourceLabels: ["__name__"]
      targetLabel: __name__
      regex: django_http_requests_latency_including_middlewares_seconds_sum
      replacement: http_request_duration_seconds_sum
    - action: replace
      sourceLabels: ["__name__"]
      targetLabel: __name__
      regex: django_http_requests_latency_including_middlewares_seconds_count
      replacement: http_request_duration_seconds_count
{{- end }}
{{- end }}
