apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gather
spec:
  replicas: {{ .Values.gather.count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-gather
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-gather
    spec:
      containers:
        - name: harvest-gather
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "ckan" "files" $.Files) }}'
          imagePullPolicy: Always
          volumeMounts:
            - name: production-ini
              mountPath: /config
              readOnly: true
          command: ["/bin/sh", "-c"]
          args: ["ckan harvester gather-consumer"]
          env:
            {{ include "ckan.environment-variables" . | nindent 12 }}
      volumes:
        - name: production-ini
          configMap:
            name: {{ .Release.Name }}-ckan-production-ini
