apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ckan-init
data:
  init.sh: |
    # copy production.ini
    cp /map/production.ini /config

    # update production.ini
    ckan config-tool $CKAN_INI "beaker.session.secret=$CKAN_BEAKER_SESSION_SECRET"

    {{- if $.Values.dev.enabled }}
    ckan config-tool $CKAN_INI "ckan.datagovuk.s3_aws_access_key_id = $CKAN_AWS_ACCESS_KEY_ID"
    ckan config-tool $CKAN_INI "ckan.datagovuk.s3_aws_secret_access_key = $CKAN_AWS_ACCESS_KEY_SECRET"
    {{- end }}

    # run init script
    /ckan-entrypoint.sh
