apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ckan
spec:
  selector:
    app: {{ .Release.Name }}-ckan
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: http
