{{- if .Values.ckan.serviceAccount.enabled }}
{{- with .Values.ckan.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | default (print "ckan-" $.Release.Name) }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .iamRoleARN }}
{{- end }}
{{- end }}
