{{- $fullName := (print .Release.Name "-check-links-output") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-script
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ $fullName }}
data:
  download-and-wait.sh: |-
    cd /usr/lib/ckan/venv/src/ckanext-datagovuk/bin/python_scripts
    python check_links_download.py

    # catch termination signals and wait indefinitely until the container is terminated
    trap : TERM INT; sleep infinity & wait
