apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-publish
spec:
  replicas: {{ .Values.publish.count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-publish
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-publish
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: publish
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "publish" "files" $.Files) }}'
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["tail -f /dev/null"]
          env:
            {{ include "publish.environment-variables" . | nindent 12 }}
      volumes:
        - name: publish-init
          configMap:
            name: {{ .Release.Name }}-publish-init
