apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-publish
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.publish.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-publish
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-publish
    spec:
      initContainers:
        - name: config-set
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "publish" "files" $.Files) }}'
          command: [ "/bin/sh", "-c", '. /init/init.sh']
          imagePullPolicy: Always
          env:
            {{ include "publish.environment-variables" . | nindent 12 }}
          volumeMounts:
            - name: publish-init
              mountPath: /init
            - name: app-tmp
              mountPath: /srv/app/datagovuk_publish/tmp
      containers:
        - name: publish
          image: '{{ include "docker-uri" (dict "environment" .Values.environment "app" "publish" "files" $.Files) }}'
          imagePullPolicy: Always
          env:
            {{ include "publish.environment-variables" . | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.monitoring.metricsPort }}
      volumes:
        - name: publish-init
          configMap:
            name: {{ .Release.Name }}-publish-init
        - name: app-tmp
          emptyDir: {}
