apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-publish-init
data:
  init.sh: |
    if [ "$DB_SETUP" = 'yes' ]; then
      bin/rails db:setup
    fi 

    rake db:migrate db:seed

    # wait until CKAN is ready
    until [ "$health" = 'OK' ]; do
        health="$(curl -fsSL "$CKAN_URL/healthcheck")"
        if [ "$health" != 'OK' ]; then
            echo "CKAN is unavailable - sleeping"
            sleep 10
        fi
    done

    echo "CKAN is available..."
