name: Auto-Approve and Merge Integration Image Tag Updates

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - feature/DGUK-505-auto-deploy-integration
    paths:
      - 'charts/datagovuk/images/integration/datagovuk.yaml'

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.title, 'Update datagovuk image tags for integration')

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Verify PR Author
        env:
         PR_GITHUB_TOKEN_USERNAME: ${{ secrets.PR_GITHUB_TOKEN_USERNAME }}
        run: |
          if [ "${{ github.event.pull_request.user.login }}" != "$PR_GITHUB_TOKEN_USERNAME" ]; then
            echo "Unexpected PR author"; exit 1
          fi
      - name: Approve the PR
        env:
          GH_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} \
            --approve \
            --body "Automated approval for datagovuk integration image tag updates." \
            --repo ${{ github.repository }}

      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --auto \
            --merge \
            --delete-branch \
            --repo ${{ github.repository }}
